### PR TITLE
Add braces in single-line blocks #18

### PR DESCRIPTION
**Pull request by paulohrpinheiro**
Add braces in single-line blocks (issue #18 ), in files under /src, /lib and /include dirs.

### CODE REVIEW

**Comment by spbnick** [comment]
Excellent work, Paulo, thank you very much! Everything is fine and clean. I only found three more bare blocks and also fixed formatting of two ifs. I also fixed up your commit message a little. I created #74 with those, so CI can run on it and you can take a look.

**Comment by spbnick** [comment]
I also rebased the commit so the history would stay straight.

BTW, if you would like to do some more work on tlog, I tagged some more easy issues: https://github.com/Scribery/tlog/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy
or just take whatever interests you!

**Comment by paulohrpinheiro** [comment]
Again, thank you for the opportunity. It was nice to know the project 
and to read quality code.

If I can help in something else, I am available.

Until next time!

--
Paulo Henrique Rodrigues Pinheiro
https://about.me/paulohrpinheiro

Em 07-10-2016 12:45, Nikolai Kondrashov escreveu:

**Comment by spbnick** [comment]
Awesome :) Just choose whatever interests you from the issues for the start, and feel free to ask questions!

**Comment by spbnick** [comment]
Of the "easy" issues the most needed right now are #16 and #45.

**Pull request closed without merging**
