### PR TITLE
travis-ci integration

### PR DESCRIPTION
**Pull request by dkopecek**
Hello,
this is an attempt to integrate the Scribery/tlog repository with the travis-ci CI platform. I guess I'll need admin access to the organization to complete the integration, or you (@spbnick) will have to do it. What needs to be done is:
 - [x] Create the travis-ci Scribery account (log in via Github)
 - [x] Enable and configure the repository at travis-ci.org

### CODE REVIEW

**Comment by spbnick** [comment]
Thanks, Daniel! I made you an admin. Please set up the travis-ci side. I have two comments on the patch, though.

**Comment by dkopecek** [comment]
@spbnick I use out-of-tree builds for mainly for 2 reasons:
 1. to not pollute the sources with various build generates files
 2. to catch bugs in Makefiles

Otherwise there are no real benefits I guess.

**Comment by dkopecek** [comment]
@spbnick regarding --enable-debug, yes, we should do CI with that option as well. I'd like to add some testing matrix as we should test a combination of some options. I'll add that later, after we get to a working integration.

Another idea in the queue is code coverage of the test suite (another badge we can add to the main page). And of course the static code analysis. Both will come later via pull requests.

**Comment by spbnick** [comment]
Well, I do use in-tree builds and I'd like to have that tested in CI, if possible. OTOH, `make distcheck` tests out-of-tree builds, AFAIK. Moreover it does that with the source tree read-only. Would that be enough to test your out-of-tree building? Or am I missing something?

Perhaps as `make distcheck` does a distribution first and then builds from a tarball instead of the actual git tree, it can miss some files which would interfere otherwise? Or would it be a problem for travis-ci if we did an in-tree build?

**Comment by spbnick** [comment]
Otherwise, awesome ideas, I support them fully :+1: :)

**Comment by dkopecek** [comment]
@spbnick ok, I'll change that to an in-tree build.

**Comment by spbnick** [comment]
@dkopecek Thanks! Please feel free to raise the issue if it doesn't work for you after all.

**Comment by spbnick** [comment]
@dkopecek Could you please squash these two commits into one?

**Comment by dkopecek** [comment]
@spbnick done

**Comment by spbnick** [comment]
Thanks!

**Comment by spbnick** [comment]
Another idea can be building RPMs. Ubuntu should have rpmbuild, as Debian has it.

**Pull request merged**
